<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Maddy" name="week4.testng.contact.tcs.DeactivateContactUsingInterface" tests="1" failures="0" timestamp="31 Mar 2018 06:12:24 GMT" time="37.401" errors="1">
  <testcase name="deactivateContactTC" time="37.401" classname="week4.testng.contact.tcs.DeactivateContactUsingInterface">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at wdMethods.SeMethods.locateElement(SeMethods.java:91)
at week4.testng.contact.tcs.DeactivateContactUsingInterface.deactivateContactTC(DeactivateContactUsingInterface.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- deactivateContactTC -->
</testsuite> <!-- week4.testng.contact.tcs.DeactivateContactUsingInterface -->
